# Generated by Django 4.0.3 on 2022-04-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professeurs',
            fields=[
                ('code_prof', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nom_prof', models.CharField(max_length=50)),
            ],
        ),
    ]
