# Generated by Django 4.0.3 on 2022-05-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_promotion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_semester', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Td',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_td', models.CharField(max_length=5)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, choices=[('professeur', 'Professeur'), ('vacataire', 'Vacataire')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_week', models.DateField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Tp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tp', models.CharField(max_length=5)),
                ('td', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.td')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subject', models.CharField(max_length=20)),
                ('number_cm_sessions', models.PositiveIntegerField(default=0)),
                ('number_td_sessions', models.PositiveIntegerField(default=0)),
                ('number_tp_sessions', models.PositiveIntegerField(default=0)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sessions', models.CharField(blank=True, choices=[('cm', 'Cm'), ('td', 'Td'), ('tp', 'Tp')], max_length=20)),
                ('number_sessions', models.PositiveIntegerField(default=0)),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='management.promotion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.subject')),
                ('td', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='td', to='management.td')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.teacher')),
                ('tp', models.ManyToManyField(blank=True, related_name='tp', to='management.tp')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.week')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.year'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.year'),
        ),
    ]
