# Generated by Django 4.0.3 on 2022-04-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professeurs',
            fields=[
                ('code_prof', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nom_prof', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetailService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_enseignement', models.IntegerField()),
                ('type', models.CharField(max_length=8)),
                ('nombre', models.IntegerField()),
                ('code_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.professeurs')),
            ],
            options={
                'unique_together': {('code_enseignement', 'type')},
            },
        ),
    ]
