# Generated by Django 4.0.3 on 2022-04-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_enseignement', models.IntegerField()),
                ('type_ds', models.CharField(max_length=8)),
                ('nombre', models.IntegerField()),
                ('code_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.professeurs')),
            ],
            options={
                'unique_together': {('code_enseignement', 'type_ds')},
            },
        ),
    ]
