# Generated by Django 4.0.3 on 2022-04-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailservice',
            old_name='type',
            new_name='type_ds',
        ),
        migrations.AlterUniqueTogether(
            name='detailservice',
            unique_together={('code_enseignement', 'type_ds')},
        ),
    ]
