# Generated by Django 4.0.3 on 2022-05-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_sessions_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='week',
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='management.sessions')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week', to='management.week')),
            ],
        ),
    ]
