# Generated by Django 4.0.3 on 2022-04-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_sessions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='type',
            field=models.CharField(blank=True, choices=[('cm', 'Cm'), ('td', 'Td'), ('tp', 'Tp')], max_length=20),
        ),
    ]
