# Generated by Django 4.0.3 on 2022-05-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_sessions_week_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='number_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
