# Generated by Django 4.0.3 on 2022-04-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_sessions_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='type',
            new_name='type_sessions',
        ),
    ]
