# Generated by Django 4.0.3 on 2022-04-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_typesens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveaux',
            fields=[
                ('code_niveau', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nom_niveau', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ues',
            fields=[
                ('code_ue', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('libelle_ue', models.CharField(max_length=80)),
                ('coef_ue', models.DateField()),
                ('code_semestre', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Unites',
            fields=[
                ('code_unite', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('libelle_unite', models.CharField(max_length=100)),
                ('annee', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Semestres',
            fields=[
                ('code_semestre', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nom_semestre', models.CharField(max_length=80)),
                ('groups_td', models.IntegerField()),
                ('groups_tp', models.IntegerField()),
                ('code_niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.niveaux')),
            ],
        ),
        migrations.CreateModel(
            name='Periodes',
            fields=[
                ('code_periode', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nom_periodes', models.CharField(max_length=80)),
                ('code_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.semestres')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('code_module', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('libelle_module', models.CharField(max_length=80)),
                ('coef_module', models.FloatField()),
                ('code_ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ues')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_semaines', models.FloatField()),
                ('n_cours', models.FloatField()),
                ('n_td', models.FloatField()),
                ('n_tp', models.FloatField()),
                ('remarque', models.CharField(max_length=500)),
                ('code_enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.detailservice')),
                ('code_periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.periodes')),
                ('code_unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.unites')),
            ],
        ),
    ]
