# Generated by Django 4.0.3 on 2022-05-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_planning_number_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='sessions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.sessions'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.week'),
        ),
    ]
