version: "3.9"
   
services:
  app:
    build: .
    container_name: ${NAME}

  app_run:
    extends:
      service: app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    networks:
      - web  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcandev.netlib.re`)"
      - "traefik.http.routers.${NAME}.entrypoints=websecure"
      - "traefik.http.routers.${NAME}.tls.certresolver=lets-encrypt"  

networks:
  web:
    external: true

